# Site settings
title: "Arquiteturas Modulares"
description: "10 Princípios para Construir Sistemas Evolutivos"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Theme - Cayman provides clean, professional styling ideal for whitepapers
theme: jekyll-theme-cayman

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections (if needed later)
collections:
  sections:
    output: true
    permalink: /:collection/:name

