# Site settings
title: "Arquiteturas Modulares"
description: "10 Princípios para Construir Sistemas Evolutivos"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://modular-architectures.com" # your actual domain

# No theme - using custom minimal layout

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  hard_wrap: false
  parse_block_html: true

# Plugins (only GitHub Pages approved plugins)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap