# Site settings
title: "Arquiteturas Modulares"
description: "10 Princípios para Construir Sistemas Evolutivos"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Theme - Cayman provides clean, professional styling ideal for whitepapers
layout: jekyll-theme-cayman


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mermaid